spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  data:
    rest:
      base-path: /v2
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    restart:
      enabled: false
  profiles:
    active: dev


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9999

logging:
  file: nvr.log